In [11]:
import numpy as np
import sys
import array

## 1. Типы данных

In [5]:
x = 1
print(type(x))
print(sys.getsizeof(x))

<class 'int'>
28


In [2]:
x = 'hello'
print(type(x))

<class 'str'>


In [3]:
x = True
print(type(x))

<class 'bool'>


In [6]:
l1 = list([])
print(sys.getsizeof(l1))

56


In [7]:
l2 = list([1, 2, 3])
print(sys.getsizeof(l2))

88


In [8]:
l3 = list([1, '2', True])
print(sys.getsizeof(l3))

88


In [12]:
a1 = array.array('i', [1, 2, 3])
print(sys.getsizeof(a1))
print(type(a1))

92
<class 'array.array'>


## 2. Numpy

In [13]:
a = np.array([1, 2, 3, 4 ,5])

In [15]:
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [16]:
# повышающее приведение типов
a = np.array([1.0, 2, 3, 4 ,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]


In [17]:
# явное приведение типов
a = np.array([1.0, 2, 3, 4 ,5], dtype=int)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [19]:
# многомерные массивы
a = np.array([range(i, i+3) for i in [2, 4, 6]])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [23]:
a = np.zeros(10, dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [24]:
a = np.ones((3, 5), dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
a = np.full((4, 4), 3.1415)
print(a)

[[3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415]]


In [26]:
a = np.arange(0, 20, 2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [27]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 3. Массивы

In [28]:
np.random.seed(1)

In [29]:
x1 = np.random.randint(10, size=3)
print(x1)

[5 8 9]


In [30]:
x2 = np.random.randint(10, size=(3, 2))
print(x2)

[[5 0]
 [0 1]
 [7 6]]


In [33]:
x3 = np.random.randint(10, size=(3, 2, 2))
print(x3)

[[[2 4]
  [7 7]]

 [[9 1]
  [7 0]]

 [[6 9]
  [9 7]]]


In [34]:
print(x1.ndim, x1.shape, x1.size)
print(x2.ndim, x2.shape, x2.size)
print(x3.ndim, x3.shape, x3.size)

1 (3,) 3
2 (3, 2) 6
3 (3, 2, 2) 12


In [36]:
a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[-2])

1
4


In [37]:
a[1] = 20
print(a)

[ 1 20  3  4  5]


In [39]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [41]:
print(a[0,0])
print(a[-1,-1])

1
6


In [42]:
a[1, 0] = 100
print(a)

[[  1   2   3]
 [100   5   6]]


In [43]:
a = np.array([1, 2, 3, 4])

In [44]:
a[0] = 10
print(a)

[10  2  3  4]


In [45]:
a[1] = 10.1
print(a)

[10 10  3  4]


In [51]:
a = np.array([1, 2, 3, 4, 5])
print(a[:3])
print(a[3:])
print(a[1:4])
print(a[1::2])

[1 2 3]
[4 5]
[2 3 4]
[2 4]


In [52]:
a = np.array([1, 2, 3, 4])

In [53]:
b = a[:3]
print(b)

[1 2 3]


In [54]:
b[0] = 100
print(a)

[100   2   3   4]


In [56]:
a = np.arange(1, 13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [57]:
print(a.reshape(2, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [59]:
print(a.reshape(4, 3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [60]:
x = np.array([1, 2, 3])
y = np.array([4, 6])
z = np.array([6])

In [61]:
print(np.concatenate([x, y, z]))

[1 2 3 4 6 6]


In [62]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [63]:
r1 = np.vstack([x, y])
print(r1)

[[1 2 3]
 [4 5 6]]


In [64]:
print(np.hstack([r1, r1]))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## 4. Вычисления с массивами

In [65]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [66]:
print(2 * x + 1)

[ 1  3  5  7  9 11 13 15 17 19]


In [68]:
print(np.add(np.multiply(x, 2), 1))

[ 1  3  5  7  9 11 13 15 17 19]


In [69]:
y = np.empty(10)
print(np.multiply(x, 10, out=y))

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [70]:
print(y)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [71]:
x = np.arange(1, 5)
print(x)

[1 2 3 4]


In [72]:
print(np.add.reduce(x))

10


In [73]:
print(np.add.accumulate(x))

[ 1  3  6 10]


In [74]:
x = np.arange(1, 10)
print(np.add.outer(x, x))

[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]
